services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - MongoDbSettings__ConnectionString=mongodb://admin:password123@mongodb:27017
      - MongoDbSettings__DatabaseName=millionrealestatedb
    networks:
      - million-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - million-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  million-network:
    driver: bridge
